name: Benchmark (PR)

on:
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - '!**.md'

jobs:
  Benchmark:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.19.x
          - 1.x
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install benchstat
      run: | 
        go install golang.org/x/perf/cmd/benchstat@latest
        go install github.com/msaf1980/qbenchstat/cmd/qbenchstat@latest

    - name: Setup benchmarks
      run: |
        echo "PR_COMMENT=$(mktemp)" >> $GITHUB_ENV
        echo "TMP_DIR=$(mktemp -d)" >> $GITHUB_ENV

    - name: Checkout (PR)
      uses: actions/checkout@v1

    - name: Get changes list
      id: changed
      run: |
        ./ci/changes.py -b ${{ github.event.pull_request.base.sha }} -u ${{ github.event.pull_request.head.sha }} > ${{ env.TMP_DIR }}/changes.txt
        if [ -s ${{ env.TMP_DIR }}/changes.txt ]; then
          echo "changed=${{ env.TMP_DIR }}/changes.txt" >> $GITHUB_OUTPUT
          cat ${{ env.TMP_DIR }}/changes.txt
        else
          echo "changed=" >> $GITHUB_OUTPUT
        fi

    - name: Benchmark (PR)
      if: ${{ steps.changed.outputs.changed != '' }}
      run: |
        ./ci/bechmark.py -f ${{ steps.changed.outputs.changed }} | tee ${{ env.TMP_DIR }}/bench-pr.txt

    - name: Checkout Base
      if: ${{ steps.changed.outputs.changed != '' }}
      uses: actions/checkout@v1
      with:
        ref: ${{ github.event.pull_request.base.sha }}

    - name: Benchmark (Base)
      if: ${{ steps.changed.outputs.changed != '' }}
      run: |
        ./ci/bechmark.py -f ${{ steps.changed.outputs.changed }} | tee ${{ env.TMP_DIR }}/bench-base.txt

    - name: Benchstat
      if: ${{ steps.changed.outputs.changed != '' }}
      run: |
        set -euo pipefail
        cp ${{ env.TMP_DIR }}/bench-base.txt ${{ env.TMP_DIR }}/bench-pr.txt .
        qbenchstat -increasing 'match/s' -threshold 2 -format html bench-base.txt bench-pr.txt > ${{ env.TMP_DIR }}/benchstat.html
        qbenchstat -increasing 'match/s' -format html bench-base.txt bench-pr.txt > benchstat-${{ matrix.go-version }}.html

    - name: Upload Benchstat
      if: ${{ steps.changed.outputs.changed != '' }}
      uses: actions/upload-artifact@v2
      with: 
        name: benchstat
        path: benchstat-${{ matrix.go-version }}.html

    - name: Create comment PR
      if: ${{ steps.changed.outputs.changed != '' }}
      run: |
        echo 'Benchmark comparison for golang ${{ matrix.go-version }} on [${{ github.event.pull_request.head.sha }}](${{ github.event.repository.html_url }}/commit/${{ github.event.pull_request.head.sha }}) (${{ github.event.pull_request.head.ref }}) vs [${{ github.event.pull_request.base.sha }}](${{ github.event.repository.html_url }}/commit/${{ github.event.pull_request.base.sha }}) (${{ github.event.pull_request.base.ref }})' > ${{ env.TMP_DIR }}/pr_comment
        
        echo "<details><summary>Benchmark diff</summary>" >> ${{ env.TMP_DIR }}/pr_comment
        cat ${{ env.TMP_DIR }}/benchstat.html >> ${{ env.TMP_DIR }}/pr_comment
        echo "</details>" >> ${{ env.TMP_DIR }}/pr_comment

        # echo "<details><summary>Benchmark result</summary>" >> ${{ env.TMP_DIR }}/pr_comment
        # echo '```' >> ${{ env.TMP_DIR }}/pr_comment
        # cat ${{ env.TMP_DIR }}/bench-pr.txt >> ${{ env.TMP_DIR }}/pr_comment
        # echo '```' >> ${{ env.TMP_DIR }}/pr_comment
        # echo "</details>" >> ${{ env.TMP_DIR }}/pr_comment

    - name: 'Comment PR'
      if: ${{ steps.changed.outputs.changed != '' }}
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: require('fs').readFileSync('${{ env.TMP_DIR }}/pr_comment').toString()
          });
